FORMAT: 1A

# API Introduction

## Code Redemption[/redeem/{code}]

+ **Usage**
    + Helps user to redeem 

+ **Parameters**
    + code:  `/[a-zA-Z0-9_\-]{22,}={1,2}/`
    + It is unique code for user to redeem the gift

* **Method:**
    + `POST`

*  **Response Params**

    + Success Response (application/json) 
    
            {    
                success: true,
                gifts:  [
                    {
                        id: 1,
                        redeemed_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                        created_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                        updated_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                        condition_log_id: nil,
                        deleted_at: nil,
                        entry_id: 1,
                        gift_map_id: 1,
                        redemption_token: "2uYNAeKffLQ82_5drfEdYg==",
                        point_redemption_id: nil,
                        campaign_member_id: 1   
                    }
                ]
                member: {
                        email: "abc@email.com",
                        gender: "male"
                }
            }            
    + If there is a new redemption, 
    system will create new gift history record, modify the number of the gifts and associate the gift record to the corresponding member

## Redeem gifts[/redeem_gifts/{campaign_member_token}]

+ **Usage**
    + Redeem the selected gifts by deducting membership points

+ **Parameters**
    + campaign_member_token:  `/[a-zA-Z0-9_\-]{22,}={1,2}/`
    
    + it store the member information associated with a specific campaign

* **Method:**
    + `POST`

*  **Response Params**

    + Success Response (application/json) 
    
            {    
                success: true,
                gifts:  [
                    {
                        id: 1,
                        redeemed_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                        created_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                        updated_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                        condition_log_id: nil,
                        deleted_at: nil,
                        entry_id: 1,
                        gift_map_id: 1,
                        redemption_token: "2uYNAeKffLQ82_5drfEdYg==",
                        point_redemption_id: nil,
                        campaign_member_id: 1   
                    }
                ]
                member: {
                        email: "skymatters@example.com",
                        gender: "male"
                }
            }            
    + If there is a redemption, 
    system will create new gift history record, modify the number of the gifts and associate the gift record to the corresponding member


## Redeem all the available gift[redeem_all/{campaign_member_token}]

+ **Usage**
    + Helps user to redeem all the available gift, the points will be deducted correspondingly.


+ **Parameters**
    + campaign_member_token:  `/[a-zA-Z0-9_\-]{22,}={1,2}/`
    + These campaign member token is unique and it stored the corresponding info for each member 

* **Method:**
    + `POST`

*  **Response Params**

    + Success Response (application/json)

            {
                success: true,
                gifts:  [
                    {
                    id: 1,
                    redeemed_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                    created_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                    updated_at: Thu, 25 Aug 2016 15:14:23 HKT +08:00,
                    condition_log_id: nil,
                    deleted_at: nil,
                    entry_id: 1,
                    gift_map_id: 1,
                    redemption_token: "2uYNAeKffLQ82_5drfEdYg==",
                    point_redemption_id: nil,
                    campaign_member_id: 1   
                }
                ]
                member: {
                    email: "loop@example.com",
                    gender: "female"
                }
            }      
            
    + If the redeem_all method runs successfully, system will create new gift history record, modify the number of the gifts and associate the gift record to the corresponding member

## Export codes[/export_codes]

+ **Usage**
    + It will export sky codes of the sky code batch that the user currently selected

+ **Requested Parameters**
    + There will be a form for user to input the size of the skycodes that they want to export

* **Method:**
    + `GET`

*  **Response**

    +   Success Response (application/json) 
        
            {
                success: true,
                codes: [
                    "dZpLgbnNGJrnmA7SPNIo5Q==", 
                    "vH-wbDEnBpAYDEE0voI2ZA==", 
                    "NZA78LVbtPiHveMCqw4nKg=="
                ]
            }
    + It will generate sky codes according to the size that the user input into a csv file.
    
## Restore the user information in input form[/member/{id}/{remember_me_token}]

+ **Usage**
    + It helps user to input the stored values in the input form thus they do no need to re-enter the user information

+ **Parameters**
    + id :  the id is stored in the params of the url

* **Method:**
    + `GET`

*  **Response Params**

    + Success Response (application/json)

            {
                success: true,
                member: {
                    email: "loop@example.com",
                    phone: "2300 0000",
                    country: "Hong Kong"
                }    
            }
    + The web will pop up a confirm box to ask user whether is a specific member, if yes then it will fill in the form with the member's information
    
## Show the profile of the member[/profile/{campaign_member_token}]

+ **Usage**
    + Show the user information as a profile and provide a link for member to download his/her pass.

+ **Parameters**
    + campaign_member_token :  

* **Method:**
    + `GET`

*  **Response Params**

    + Success Response (application/json)

            {
                success: true,
                campaign_member: {
                    email: "loop@example.com",
                    phone: "2300 0000",
                    points_stats: {},
                    gifts_stats: {},
                    pass_download_url: "http://www.example.com/api/v1/pass/LmOTqIYdg=="
                }    
            }    
    
## Parse the user profile into the pass[pass/{campaign_member_token}]

+ **Usage**
    + Get the ‘campaign member token’ from params and parse the corresponding data into the pass and return a link for user to download the pass


+ **Parameters**
    + campaign_member_token is stored in the url
    + it is a token that stored that user information within a specific campaign


* **Method:**
    + `GET`

*  **Response Params**

    + Success Response (application/json)

        
            {
                type: 'application/vnd.apple.pkpass', 
                disposition: 'attachment', 
                filename: "pass.pkpass"
            }    

## Create entries when there is new successful submission[entries]

+ **Usage**
    + 


+ **Parameters**
    + campaign_member_token is stored in the url
    + it is a token that stored that user information within a specific campaign


* **Method:**
    + `POST`

*  **Response Params**

    + Success Response (application/json)

        
            {
            success: true,
             campaign_member:{campaign_member_token: "lob9V5ZXqeNre4lUnGEDtA==},
             gifts: 
              [{name: "Gift",
                amount: 1,
                image_url: "/uploads/gift/image/1/icon.png",
                gift_id: 1,
                redemption_token: "o2mhuflvkiNkXhoTbPbntw==",
                redeemed_at: nil}]
        }
            
*  **Response Params**

    + Success Response (application/json)

            {
                success: true,
                campaign_member: {
                    email: "loop@example.com",
                    phone: "2300 0000",
                    points_stats: {},
                    gifts_stats: {},
                    pass_download_url: "http://www.example.com/api/v1/pass/LmOTqIYdg=="
                }    
            } 

## Gift index[/gifts/{campaign_member_token}]

+ **Usage**
    
    + Show the gifts in the campaign and the point balance of the member


+ **Parameters**
    
    + campaign_member_token: "zMnGD8jHnfkIFj=="


* **Method:**
    + `GET`

*  **Response Params**

    + Success Response (application/json)

            {
                success: true,
                gifts: [
                    id: 7,
                    campaign_id: 6,
                    name: "One more Gift",
                    quantity: 4,
                    created_at: Thu, 25 Aug 2016 18:06:33 HKT +08:00,
                    updated_at: Thu, 25 Aug 2016 18:06:33 HKT +08:00,
                    deleted_at: nil,
                    image: "icon.png"
                ],
                campaign_member: {
                    points_stats: {
                        vip: 100,
                        Point#2: 10
                    }
                }
            }    

## Gift select[/gifts/select/{campaign_member_token}]

+ **Usage**
    
    + Users can select gift and its quantity to redeem 


+ **Parameters**
    
    + campaign_member_token: "zMnGD8jHnfkIFj=="


* **Method:**
    + `POST`

*  **Response Params**

    + Success Response (application/json)
            
            {
                points_stats: {
                    vip: 20
                }
            }